name: handling_network_connectivity
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.3.9
  get: 4.6.5
  get_storage: ^2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.5
  stacked_generator: ^0.5.6
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

